name: 'pull-request-test-only'
on: # rebuild any PRs for main branch changes
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main 
  issue_comment:
    types: [created, edited]
    branches:
      - main

jobs:
  test: 
    name: Create Edit or Comment
    # if: ${{ github.event.issue.pull_request || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
