name: 'Contains AB# with a valid work item id'
on: # rebuild any PRs for main branch changes
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main 
jobs:
  create-edit-comment:
    name: Validate for AB#    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./